### ISSUE TITLE
Is it possible to make it non-interactive

### ISSUE THREAD

**Issue by grepsuzette** [ubunatic/ohlc#1]
Your ohlc package is pretty cool! 
However it seems that it's only possible to show **interactive** text chart right now.

It would be useful to maybe have a non-interactive option.

**Comment by grepsuzette** [comment]
Or maybe just provide an example to use the CandleCanvas from a simple file,
this way the user can write a wrapper and implement arguments (width etc).

**Comment by ubunatic** [comment]
It should be possible. Just check grab some code from the test cases.
Run `PYTHONPATH=$PWD pytest-3 -x -v -s tests/test_candle.py` and you will see some non-interactive charts.

**Comment by ubunatic** [comment]
I added support for the cli tool. Use `-n` to print a non-interactive chart.

**Comment by grepsuzette** [comment]
It works. Amazing!
Honestly you did a very nice job with this package.
I'm going to open two other minor issues though :p.
