### ISSUE TITLE
Color of bullish/bearish candles got swapped since last update

### ISSUE THREAD

**Issue by grepsuzette** [ubunatic/ohlc#5]
E.g. using `ohlc <(echo -e "8 11 7 4 5\n5 4 8 6\n6\n6 5\n5 6 1 4") --title "Input" -n`, the bullish candles seems red to me, while the bearish appears green. 

(I just tried updating with `pip install --user -U ohlc` so I think I have the last version, the one published a few days ago).

**Comment by ubunatic** [comment]
Confirmed. I did not touch the colors though. I have a very busy week, and may check the issue at the weekend. In interactive mode they are still correct. I guess something is wrong with the non-interactive quick shot.

**Comment by ubunatic** [comment]
fixed it there was a hack in the code which I forgot to take out last year ;)
Just be aware that this software is really alpha software esp. the charting part.

**Comment by grepsuzette** [comment]
(I think we might have forgotten to update it for `pip install --user -U ohlc`)
